"""DynamoDB design review application helpers (v2.0.1).

This module provides functions to apply Claude's review suggestions
to a DynamoDB design generated by DynamoDBDesigner.
"""

import copy
import logging
from typing import Optional

from schema_travels.recommender.dynamodb_models import (
    DynamoDBDesign,
    DynamoDBReview,
    EntityChange,
    EntityDefinition,
    GSIChange,
    GSIChangeAction,
    GSIDefinition,
    ReviewChangeType,
    DesignMode,
    ProjectionType,
)

logger = logging.getLogger(__name__)


def apply_review(
    design: DynamoDBDesign,
    review: DynamoDBReview,
    apply_mode_change: bool = True,
    apply_entity_changes: bool = True,
    apply_gsi_changes: bool = True,
) -> DynamoDBDesign:
    """
    Apply Claude's review suggestions to a DynamoDB design.
    
    Creates a new design with the suggested changes applied.
    The original design is not modified.
    
    Args:
        design: Original DynamoDB design from DynamoDBDesigner
        review: Claude's review with suggested changes
        apply_mode_change: Whether to apply design mode changes
        apply_entity_changes: Whether to apply entity PK/SK changes
        apply_gsi_changes: Whether to apply GSI changes
        
    Returns:
        New DynamoDBDesign with changes applied
    """
    if not review.has_changes:
        # No changes to apply - mark as reviewed and return
        result = _copy_design(design)
        result.ai_reviewed = True
        result.ai_review_applied = False
        
        # Add any warnings/suggestions from review
        result.warnings = list(set(result.warnings + review.warnings))
        result.recommendations = list(set(result.recommendations + review.suggestions))
        
        return result
    
    # Start with a copy
    result = _copy_design(design)
    result.ai_reviewed = True
    result.ai_review_applied = True
    changes_applied = 0
    
    # Apply design mode change (rare, but possible)
    if apply_mode_change and review.design_mode_change:
        old_mode = result.design_mode
        result.design_mode = review.design_mode_change
        result.rationale = f"{result.rationale} [AI changed mode from {old_mode.value} to {review.design_mode_change.value}: {review.design_mode_reason}]"
        changes_applied += 1
        logger.info(f"Applied design mode change: {old_mode.value} → {review.design_mode_change.value}")
    
    # Apply entity changes
    if apply_entity_changes and review.entity_changes:
        for change in review.entity_changes:
            if _apply_entity_change(result, change):
                changes_applied += 1
    
    # Apply GSI changes
    if apply_gsi_changes and review.gsi_changes:
        for change in review.gsi_changes:
            if _apply_gsi_change(result, change):
                changes_applied += 1
    
    # Add warnings and suggestions from review
    result.warnings = list(set(result.warnings + review.warnings))
    result.recommendations = list(set(result.recommendations + review.suggestions))
    
    # Add uncovered patterns as warnings
    for pattern in review.uncovered_patterns:
        warning = f"Access pattern may not be well-supported: {pattern}"
        if warning not in result.warnings:
            result.warnings.append(warning)
    
    # Update rationale
    if changes_applied > 0:
        result.rationale = f"{result.rationale} [AI review applied {changes_applied} changes]"
    
    # Update confidence based on review
    # Blend original confidence with review confidence
    result.confidence = (result.confidence + review.confidence) / 2
    
    logger.info(f"Applied {changes_applied} changes from AI review")
    
    return result


def _copy_design(design: DynamoDBDesign) -> DynamoDBDesign:
    """Create a deep copy of a DynamoDB design."""
    return DynamoDBDesign(
        design_mode=design.design_mode,
        confidence=design.confidence,
        rationale=design.rationale,
        table_name=design.table_name,
        partition_key=design.partition_key,
        partition_key_type=design.partition_key_type,
        sort_key=design.sort_key,
        sort_key_type=design.sort_key_type,
        entities=[
            EntityDefinition(
                name=e.name,
                source_table=e.source_table,
                pk_pattern=e.pk_pattern,
                sk_pattern=e.sk_pattern,
                pk_source_column=e.pk_source_column,
                sk_source_column=e.sk_source_column,
                attributes=list(e.attributes),
            )
            for e in design.entities
        ],
        gsis=[
            GSIDefinition(
                name=g.name,
                pk_attribute=g.pk_attribute,
                sk_attribute=g.sk_attribute,
                pk_pattern=g.pk_pattern,
                sk_pattern=g.sk_pattern,
                projection_type=g.projection_type,
                projected_attributes=list(g.projected_attributes),
                source_columns=list(g.source_columns),
                access_pattern=g.access_pattern,
                estimated_rcu_savings=g.estimated_rcu_savings,
            )
            for g in design.gsis
        ],
        tables=list(design.tables),  # Shallow copy OK for multi-table mode
        access_patterns=list(design.access_patterns),
        clusters=list(design.clusters),
        orphan_tables=list(design.orphan_tables),
        warnings=list(design.warnings),
        recommendations=list(design.recommendations),
        ai_reviewed=design.ai_reviewed,
        ai_review_applied=design.ai_review_applied,
    )


def _apply_entity_change(design: DynamoDBDesign, change: EntityChange) -> bool:
    """
    Apply an entity change to the design.
    
    Returns True if the change was applied.
    """
    # Find the entity
    entity = None
    entity_idx = None
    for idx, e in enumerate(design.entities):
        if e.name.lower() == change.entity.lower() or e.source_table.lower() == change.entity.lower():
            entity = e
            entity_idx = idx
            break
    
    if entity is None:
        logger.warning(f"Entity not found for change: {change.entity}")
        return False
    
    # Apply the change based on type
    if change.change_type == ReviewChangeType.MODIFY_PK:
        old_pattern = entity.pk_pattern
        entity.pk_pattern = change.new_value
        logger.info(f"Entity {entity.name}: PK pattern {old_pattern} → {change.new_value}")
        return True
        
    elif change.change_type == ReviewChangeType.MODIFY_SK:
        old_pattern = entity.sk_pattern
        entity.sk_pattern = change.new_value
        logger.info(f"Entity {entity.name}: SK pattern {old_pattern} → {change.new_value}")
        return True
        
    elif change.change_type == ReviewChangeType.ADD_ATTRIBUTE:
        if change.new_value not in entity.attributes:
            entity.attributes.append(change.new_value)
            logger.info(f"Entity {entity.name}: Added attribute {change.new_value}")
            return True
        return False
        
    elif change.change_type == ReviewChangeType.REMOVE_ATTRIBUTE:
        if change.new_value in entity.attributes:
            entity.attributes.remove(change.new_value)
            logger.info(f"Entity {entity.name}: Removed attribute {change.new_value}")
            return True
        return False
    
    return False


def _apply_gsi_change(design: DynamoDBDesign, change: GSIChange) -> bool:
    """
    Apply a GSI change to the design.
    
    Returns True if the change was applied.
    """
    if change.action == GSIChangeAction.ADD:
        # Check if GSI already exists
        for gsi in design.gsis:
            if gsi.name.lower() == change.gsi_name.lower():
                logger.warning(f"GSI {change.gsi_name} already exists, skipping add")
                return False
        
        # Check max GSI limit (5 per table)
        if len(design.gsis) >= 5:
            logger.warning(f"Already at max GSIs (5), cannot add {change.gsi_name}")
            design.warnings.append(f"Could not add GSI {change.gsi_name} - at max limit of 5")
            return False
        
        # Create new GSI
        new_gsi = GSIDefinition(
            name=change.gsi_name,
            pk_attribute=change.pk_attribute or "GSI_PK",
            sk_attribute=change.sk_attribute,
            projection_type=change.projection_type or ProjectionType.ALL,
            projected_attributes=change.projected_attributes,
            access_pattern=change.access_pattern or change.reason,
        )
        design.gsis.append(new_gsi)
        logger.info(f"Added GSI: {change.gsi_name}")
        return True
        
    elif change.action == GSIChangeAction.REMOVE:
        # Find and remove the GSI
        for idx, gsi in enumerate(design.gsis):
            if gsi.name.lower() == change.gsi_name.lower():
                design.gsis.pop(idx)
                logger.info(f"Removed GSI: {change.gsi_name} ({change.reason})")
                return True
        
        logger.warning(f"GSI {change.gsi_name} not found for removal")
        return False
        
    elif change.action == GSIChangeAction.MODIFY:
        # Find and modify the GSI
        for gsi in design.gsis:
            if gsi.name.lower() == change.gsi_name.lower():
                if change.pk_attribute:
                    gsi.pk_attribute = change.pk_attribute
                if change.sk_attribute:
                    gsi.sk_attribute = change.sk_attribute
                if change.projection_type:
                    gsi.projection_type = change.projection_type
                if change.projected_attributes:
                    gsi.projected_attributes = change.projected_attributes
                if change.access_pattern:
                    gsi.access_pattern = change.access_pattern
                logger.info(f"Modified GSI: {change.gsi_name}")
                return True
        
        logger.warning(f"GSI {change.gsi_name} not found for modification")
        return False
    
    return False


def summarize_review_changes(review: DynamoDBReview) -> str:
    """
    Create a human-readable summary of review changes.
    
    Args:
        review: The DynamoDB review
        
    Returns:
        Summary string suitable for console output
    """
    if not review.has_changes and review.approved:
        return "✓ Design approved with no changes"
    
    lines = []
    
    if not review.approved:
        lines.append("⚠ Design has issues requiring attention")
    
    if review.design_mode_change:
        lines.append(f"• Mode change: → {review.design_mode_change.value} ({review.design_mode_reason})")
    
    if review.entity_changes:
        lines.append(f"• {len(review.entity_changes)} entity change(s):")
        for ec in review.entity_changes:
            lines.append(f"  - {ec.entity}: {ec.change_type.value} → {ec.new_value}")
    
    if review.gsi_changes:
        lines.append(f"• {len(review.gsi_changes)} GSI change(s):")
        for gc in review.gsi_changes:
            if gc.action == GSIChangeAction.ADD:
                lines.append(f"  - ADD {gc.gsi_name} (PK: {gc.pk_attribute})")
            elif gc.action == GSIChangeAction.REMOVE:
                lines.append(f"  - REMOVE {gc.gsi_name}")
            else:
                lines.append(f"  - MODIFY {gc.gsi_name}")
    
    if review.warnings:
        lines.append(f"• {len(review.warnings)} warning(s)")
    
    if review.suggestions:
        lines.append(f"• {len(review.suggestions)} suggestion(s)")
    
    return "\n".join(lines)
