"""DynamoDB schema output formatters (v2.0.0).

Supports three output formats ("The Trinity"):
1. JSON - Default, intermediate, composable
2. Terraform HCL - aws_dynamodb_table resources
3. NoSQL Workbench JSON - For visual verification in AWS tool

Usage:
    design = DynamoDBDesigner().design(...)
    
    # JSON (default)
    json_output = DynamoDBOutputFormatter.to_json(design)
    
    # Terraform
    tf_output = DynamoDBOutputFormatter.to_terraform(design)
    
    # NoSQL Workbench
    workbench_output = DynamoDBOutputFormatter.to_nosql_workbench(design)
"""

import json
from typing import Any

from schema_travels.recommender.dynamodb_models import (
    DynamoDBDesign,
    DesignMode,
    ProjectionType,
    EntityDefinition,
    GSIDefinition,
    TableDesign,
)


class DynamoDBOutputFormatter:
    """Formats DynamoDB designs for various output targets."""
    
    # =========================================================================
    # JSON Output
    # =========================================================================
    
    @staticmethod
    def to_json(design: DynamoDBDesign, indent: int = 2) -> str:
        """
        Convert design to JSON string.
        
        This is the default, most flexible format. Can be used as input
        to other tools or for further processing.
        
        Args:
            design: DynamoDB design object
            indent: JSON indentation (default 2)
            
        Returns:
            JSON string
        """
        return json.dumps(design.to_dict(), indent=indent, default=str)
    
    @staticmethod
    def to_dict(design: DynamoDBDesign) -> dict[str, Any]:
        """Convert design to dictionary."""
        return design.to_dict()
    
    # =========================================================================
    # Terraform HCL Output
    # =========================================================================
    
    @staticmethod
    def to_terraform(
        design: DynamoDBDesign,
        provider_alias: str | None = None,
        tags: dict[str, str] | None = None,
    ) -> str:
        """
        Generate Terraform HCL for aws_dynamodb_table resources.
        
        Args:
            design: DynamoDB design object
            provider_alias: Optional provider alias (e.g., "aws.us-east-1")
            tags: Optional tags to apply to all resources
            
        Returns:
            Terraform HCL string
        """
        lines = []
        
        # Header comment
        lines.append("# =============================================================================")
        lines.append("# DynamoDB Tables - Generated by schema-travels v2.0.0")
        lines.append(f"# Design Mode: {design.design_mode.value}")
        lines.append("# =============================================================================")
        lines.append("")
        
        if design.design_mode == DesignMode.SINGLE_TABLE:
            # Single table with multiple entities
            lines.append(DynamoDBOutputFormatter._terraform_single_table(
                design, provider_alias, tags
            ))
        else:
            # Multiple tables
            for table in design.tables:
                lines.append(DynamoDBOutputFormatter._terraform_table(
                    table, provider_alias, tags
                ))
                lines.append("")
        
        return "\n".join(lines)
    
    @staticmethod
    def _terraform_single_table(
        design: DynamoDBDesign,
        provider_alias: str | None,
        tags: dict[str, str] | None,
    ) -> str:
        """Generate Terraform for single-table design."""
        lines = []
        
        table_name = design.table_name or "main_table"
        resource_name = DynamoDBOutputFormatter._to_resource_name(table_name)
        
        lines.append(f'resource "aws_dynamodb_table" "{resource_name}" {{')
        
        if provider_alias:
            lines.append(f'  provider = {provider_alias}')
        
        lines.append(f'  name         = "{table_name}"')
        lines.append('  billing_mode = "PAY_PER_REQUEST"')
        lines.append(f'  hash_key     = "{design.partition_key}"')
        
        if design.sort_key:
            lines.append(f'  range_key    = "{design.sort_key}"')
        
        lines.append("")
        
        # Attribute definitions
        lines.append(f'  attribute {{')
        lines.append(f'    name = "{design.partition_key}"')
        lines.append(f'    type = "{design.partition_key_type}"')
        lines.append('  }')
        
        if design.sort_key:
            lines.append("")
            lines.append(f'  attribute {{')
            lines.append(f'    name = "{design.sort_key}"')
            lines.append(f'    type = "{design.sort_key_type}"')
            lines.append('  }')
        
        # GSI attributes and definitions
        for gsi in design.gsis:
            lines.append("")
            lines.append(f'  attribute {{')
            lines.append(f'    name = "{gsi.pk_attribute}"')
            lines.append('    type = "S"')
            lines.append('  }')
            
            if gsi.sk_attribute:
                lines.append("")
                lines.append(f'  attribute {{')
                lines.append(f'    name = "{gsi.sk_attribute}"')
                lines.append('    type = "S"')
                lines.append('  }')
            
            lines.append("")
            lines.append(DynamoDBOutputFormatter._terraform_gsi(gsi))
        
        # Tags
        if tags:
            lines.append("")
            lines.append("  tags = {")
            for key, value in tags.items():
                lines.append(f'    {key} = "{value}"')
            lines.append("  }")
        
        lines.append("}")
        
        # Add entity documentation as comments
        if design.entities:
            lines.append("")
            lines.append("# Entity Patterns:")
            for entity in design.entities:
                lines.append(f"# - {entity.name}: PK={entity.pk_pattern}, SK={entity.sk_pattern}")
        
        return "\n".join(lines)
    
    @staticmethod
    def _terraform_table(
        table: TableDesign,
        provider_alias: str | None,
        tags: dict[str, str] | None,
    ) -> str:
        """Generate Terraform for a single table in multi-table design."""
        lines = []
        
        resource_name = DynamoDBOutputFormatter._to_resource_name(table.table_name)
        
        lines.append(f'resource "aws_dynamodb_table" "{resource_name}" {{')
        
        if provider_alias:
            lines.append(f'  provider = {provider_alias}')
        
        lines.append(f'  name         = "{table.table_name}"')
        lines.append(f'  billing_mode = "{table.billing_mode}"')
        lines.append(f'  hash_key     = "{table.partition_key}"')
        
        if table.sort_key:
            lines.append(f'  range_key    = "{table.sort_key}"')
        
        lines.append("")
        
        # Attribute definitions
        lines.append(f'  attribute {{')
        lines.append(f'    name = "{table.partition_key}"')
        lines.append(f'    type = "{table.partition_key_type}"')
        lines.append('  }')
        
        if table.sort_key:
            lines.append("")
            lines.append(f'  attribute {{')
            lines.append(f'    name = "{table.sort_key}"')
            lines.append(f'    type = "{table.sort_key_type}"')
            lines.append('  }')
        
        # GSIs
        for gsi in table.gsis:
            lines.append("")
            lines.append(f'  attribute {{')
            lines.append(f'    name = "{gsi.pk_attribute}"')
            lines.append('    type = "S"')
            lines.append('  }')
            
            if gsi.sk_attribute:
                lines.append("")
                lines.append(f'  attribute {{')
                lines.append(f'    name = "{gsi.sk_attribute}"')
                lines.append('    type = "S"')
                lines.append('  }')
            
            lines.append("")
            lines.append(DynamoDBOutputFormatter._terraform_gsi(gsi))
        
        # Tags
        if tags:
            lines.append("")
            lines.append("  tags = {")
            for key, value in tags.items():
                lines.append(f'    {key} = "{value}"')
            lines.append("  }")
        
        lines.append("}")
        
        return "\n".join(lines)
    
    @staticmethod
    def _terraform_gsi(gsi: GSIDefinition) -> str:
        """Generate Terraform GSI block."""
        lines = []
        
        lines.append(f'  global_secondary_index {{')
        lines.append(f'    name            = "{gsi.name}"')
        lines.append(f'    hash_key        = "{gsi.pk_attribute}"')
        
        if gsi.sk_attribute:
            lines.append(f'    range_key       = "{gsi.sk_attribute}"')
        
        lines.append(f'    projection_type = "{gsi.projection_type.value}"')
        
        if gsi.projection_type == ProjectionType.INCLUDE and gsi.projected_attributes:
            attrs = ", ".join(f'"{a}"' for a in gsi.projected_attributes)
            lines.append(f'    non_key_attributes = [{attrs}]')
        
        lines.append('  }')
        
        return "\n".join(lines)
    
    @staticmethod
    def _to_resource_name(table_name: str) -> str:
        """Convert table name to valid Terraform resource name."""
        # Replace invalid characters with underscores
        name = table_name.replace("-", "_").replace(".", "_")
        # Ensure starts with letter
        if name[0].isdigit():
            name = "table_" + name
        return name
    
    # =========================================================================
    # NoSQL Workbench JSON Output
    # =========================================================================
    
    @staticmethod
    def to_nosql_workbench(
        design: DynamoDBDesign,
        model_name: str = "SchemaTravel Model",
    ) -> str:
        """
        Generate NoSQL Workbench JSON for visual verification.
        
        NoSQL Workbench is AWS's free tool for visualizing and designing
        DynamoDB schemas. This format can be imported directly.
        
        Args:
            design: DynamoDB design object
            model_name: Name for the data model
            
        Returns:
            NoSQL Workbench JSON string
        """
        model = DynamoDBOutputFormatter._build_workbench_model(design, model_name)
        return json.dumps(model, indent=2)
    
    @staticmethod
    def _build_workbench_model(
        design: DynamoDBDesign,
        model_name: str,
    ) -> dict[str, Any]:
        """Build NoSQL Workbench data model structure."""
        model = {
            "ModelName": model_name,
            "ModelMetadata": {
                "Author": "schema-travels",
                "DateCreated": None,  # Will be set on import
                "DateLastModified": None,
                "Description": f"Generated from SQL analysis. Mode: {design.design_mode.value}",
                "Version": "2.0.0",
            },
            "DataModel": [],
        }
        
        if design.design_mode == DesignMode.SINGLE_TABLE:
            model["DataModel"].append(
                DynamoDBOutputFormatter._workbench_single_table(design)
            )
        else:
            for table in design.tables:
                model["DataModel"].append(
                    DynamoDBOutputFormatter._workbench_table(table)
                )
        
        return model
    
    @staticmethod
    def _workbench_single_table(design: DynamoDBDesign) -> dict[str, Any]:
        """Generate NoSQL Workbench table definition for single-table design."""
        table_name = design.table_name or "MainTable"
        
        # Key schema
        key_schema = [
            {
                "AttributeName": design.partition_key,
                "KeyType": "HASH",
            }
        ]
        
        if design.sort_key:
            key_schema.append({
                "AttributeName": design.sort_key,
                "KeyType": "RANGE",
            })
        
        # Attribute definitions
        attribute_defs = [
            {
                "AttributeName": design.partition_key,
                "AttributeType": design.partition_key_type,
            }
        ]
        
        if design.sort_key:
            attribute_defs.append({
                "AttributeName": design.sort_key,
                "AttributeType": design.sort_key_type,
            })
        
        # GSIs
        gsis = []
        for gsi in design.gsis:
            gsi_def = {
                "IndexName": gsi.name,
                "KeySchema": [
                    {
                        "AttributeName": gsi.pk_attribute,
                        "KeyType": "HASH",
                    }
                ],
                "Projection": {
                    "ProjectionType": gsi.projection_type.value,
                },
            }
            
            if gsi.sk_attribute:
                gsi_def["KeySchema"].append({
                    "AttributeName": gsi.sk_attribute,
                    "KeyType": "RANGE",
                })
            
            if gsi.projection_type == ProjectionType.INCLUDE and gsi.projected_attributes:
                gsi_def["Projection"]["NonKeyAttributes"] = gsi.projected_attributes
            
            gsis.append(gsi_def)
            
            # Add GSI attributes to attribute definitions
            if not any(a["AttributeName"] == gsi.pk_attribute for a in attribute_defs):
                attribute_defs.append({
                    "AttributeName": gsi.pk_attribute,
                    "AttributeType": "S",
                })
            
            if gsi.sk_attribute and not any(a["AttributeName"] == gsi.sk_attribute for a in attribute_defs):
                attribute_defs.append({
                    "AttributeName": gsi.sk_attribute,
                    "AttributeType": "S",
                })
        
        table_def = {
            "TableName": table_name,
            "KeyAttributes": {
                "PartitionKey": {
                    "AttributeName": design.partition_key,
                    "AttributeType": design.partition_key_type,
                },
            },
            "NonKeyAttributes": DynamoDBOutputFormatter._workbench_non_key_attrs(design.entities),
            "TableFacets": DynamoDBOutputFormatter._workbench_facets(design.entities),
            "GlobalSecondaryIndexes": gsis if gsis else None,
            "DataAccess": {
                "MySql": {},
            },
        }
        
        if design.sort_key:
            table_def["KeyAttributes"]["SortKey"] = {
                "AttributeName": design.sort_key,
                "AttributeType": design.sort_key_type,
            }
        
        # Remove None values
        table_def = {k: v for k, v in table_def.items() if v is not None}
        
        return table_def
    
    @staticmethod
    def _workbench_table(table: TableDesign) -> dict[str, Any]:
        """Generate NoSQL Workbench table definition for multi-table design."""
        key_schema = [
            {
                "AttributeName": table.partition_key,
                "KeyType": "HASH",
            }
        ]
        
        if table.sort_key:
            key_schema.append({
                "AttributeName": table.sort_key,
                "KeyType": "RANGE",
            })
        
        table_def = {
            "TableName": table.table_name,
            "KeyAttributes": {
                "PartitionKey": {
                    "AttributeName": table.partition_key,
                    "AttributeType": table.partition_key_type,
                },
            },
            "NonKeyAttributes": [],
            "DataAccess": {
                "MySql": {},
            },
        }
        
        if table.sort_key:
            table_def["KeyAttributes"]["SortKey"] = {
                "AttributeName": table.sort_key,
                "AttributeType": table.sort_key_type or "S",
            }
        
        # GSIs
        if table.gsis:
            gsis = []
            for gsi in table.gsis:
                gsi_def = {
                    "IndexName": gsi.name,
                    "KeySchema": [
                        {
                            "AttributeName": gsi.pk_attribute,
                            "KeyType": "HASH",
                        }
                    ],
                    "Projection": {
                        "ProjectionType": gsi.projection_type.value,
                    },
                }
                
                if gsi.sk_attribute:
                    gsi_def["KeySchema"].append({
                        "AttributeName": gsi.sk_attribute,
                        "KeyType": "RANGE",
                    })
                
                gsis.append(gsi_def)
            
            table_def["GlobalSecondaryIndexes"] = gsis
        
        return table_def
    
    @staticmethod
    def _workbench_non_key_attrs(entities: list[EntityDefinition]) -> list[dict[str, str]]:
        """Generate non-key attributes from entity definitions."""
        attrs = set()
        
        for entity in entities:
            for attr in entity.attributes:
                attrs.add(attr)
        
        return [
            {"AttributeName": attr, "AttributeType": "S"}
            for attr in sorted(attrs)
        ]
    
    @staticmethod
    def _workbench_facets(entities: list[EntityDefinition]) -> list[dict[str, Any]]:
        """Generate table facets (entity types) for NoSQL Workbench."""
        facets = []
        
        for entity in entities:
            facet = {
                "FacetName": entity.name,
                "KeyAttributeAlias": {
                    "PartitionKeyAlias": entity.pk_pattern,
                    "SortKeyAlias": entity.sk_pattern,
                },
                "NonKeyAttributes": entity.attributes,
            }
            facets.append(facet)
        
        return facets
    
    # =========================================================================
    # Convenience Methods
    # =========================================================================
    
    @staticmethod
    def format(
        design: DynamoDBDesign,
        output_format: str = "json",
        **kwargs,
    ) -> str:
        """
        Format design to specified output format.
        
        Args:
            design: DynamoDB design object
            output_format: One of "json", "terraform", "nosql_workbench"
            **kwargs: Format-specific options
            
        Returns:
            Formatted string
            
        Raises:
            ValueError: If format is not recognized
        """
        formatters = {
            "json": DynamoDBOutputFormatter.to_json,
            "terraform": DynamoDBOutputFormatter.to_terraform,
            "tf": DynamoDBOutputFormatter.to_terraform,
            "hcl": DynamoDBOutputFormatter.to_terraform,
            "nosql_workbench": DynamoDBOutputFormatter.to_nosql_workbench,
            "workbench": DynamoDBOutputFormatter.to_nosql_workbench,
        }
        
        output_format = output_format.lower()
        
        if output_format not in formatters:
            valid = ", ".join(sorted(set(formatters.keys())))
            raise ValueError(f"Unknown format '{output_format}'. Valid formats: {valid}")
        
        return formatters[output_format](design, **kwargs)
    
    @staticmethod
    def save(
        design: DynamoDBDesign,
        filepath: str,
        output_format: str | None = None,
        **kwargs,
    ) -> None:
        """
        Save design to file.
        
        Format is inferred from file extension if not specified:
        - .json → JSON
        - .tf, .hcl → Terraform
        - .workbench.json → NoSQL Workbench
        
        Args:
            design: DynamoDB design object
            filepath: Output file path
            output_format: Explicit format (overrides extension inference)
            **kwargs: Format-specific options
        """
        # Infer format from extension
        if output_format is None:
            if filepath.endswith(".tf") or filepath.endswith(".hcl"):
                output_format = "terraform"
            elif filepath.endswith(".workbench.json"):
                output_format = "nosql_workbench"
            else:
                output_format = "json"
        
        content = DynamoDBOutputFormatter.format(design, output_format, **kwargs)
        
        with open(filepath, "w") as f:
            f.write(content)
